# Agent System Configuration

system:
  name: "Web Development Agent System"
  version: "0.1.0"
  log_level: "INFO"
  max_concurrent_agents: 5

research_team:
  trend_researcher:
    sources:
      - "dribbble.com"
      - "awwwards.com"
      - "behance.net"
      - "pinterest.com"
    update_frequency: "daily"
    trend_categories:
      - "colors"
      - "typography"
      - "layouts"
      - "animations"
      - "interactions"
  
  ux_researcher:
    metrics:
      - "page_load_time"
      - "time_to_interactive"
      - "user_flow_completion_rate"
    benchmarks:
      - "google_lighthouse"
      - "web_vitals"
  
  technology_scout:
    frameworks_to_monitor:
      - "react"
      - "vue"
      - "angular"
      - "svelte"
      - "next.js"
    libraries_to_monitor:
      - "tailwind"
      - "bootstrap"
      - "material-ui"
      - "framer-motion"

design_interpreter:
  asset_generator:
    formats:
      - "svg"
      - "png"
      - "webp"
    optimization: true
  
  style_translator:
    output_formats:
      - "css"
      - "scss"
      - "tailwind_config"
      - "styled_components"
  
  animation_developer:
    libraries:
      - "gsap"
      - "framer-motion"
      - "anime.js"
      - "lottie"

planning_team:
  architecture_planner:
    patterns:
      - "mvc"
      - "flux"
      - "microservices"
    documentation_format: "markdown"
  
  component_planner:
    component_library: "storybook"
    atomic_design: true
  
  data_flow_designer:
    state_management:
      - "redux"
      - "context_api"
      - "zustand"

development_team:
  frontend_developer:
    frameworks:
      - "react"
      - "next.js"
    testing: "jest"
  
  backend_developer:
    frameworks:
      - "fastapi"
      - "express"
    testing: "pytest"
  
  database_engineer:
    databases:
      - "postgresql"
      - "mongodb"
    orm: "prisma"
  
  integration_specialist:
    api_documentation: "swagger"
    monitoring: "sentry"

security_team:
  vulnerability_scanner:
    tools:
      - "owasp_zap"
      - "snyk"
    scan_frequency: "daily"
  
  authentication_expert:
    methods:
      - "oauth2"
      - "jwt"
      - "passwordless"
  
  data_protection_specialist:
    compliance:
      - "gdpr"
      - "ccpa"
    encryption: "aes-256"
  
  penetration_tester:
    methods:
      - "xss"
      - "sql_injection"
      - "csrf"

deployment_team:
  infrastructure_manager:
    providers:
      - "aws"
      - "gcp"
      - "azure"
    iac: "terraform"
  
  cicd_engineer:
    pipeline: "github_actions"
    stages:
      - "build"
      - "test"
      - "deploy"
  
  performance_optimizer:
    metrics:
      - "lighthouse_score"
      - "web_vitals"
    caching: true
  
  monitoring_specialist:
    tools:
      - "prometheus"
      - "grafana"
    alerts: true